### ISSUE TITLE
Demo and Annotations Upgrade

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/android_remocons#1]
_ToDo_
- [x] chatter concert and rocon remocon compile/test
- [x] headless launcher compile ([#52](https://github.com/rosjava/android_remocons/issues/52))
- [x] headless launcher protocol upgrade [#53](https://github.com/rosjava/android_remocons/issues/53)
- [x] nfc_rocon_writer protocol upgrade [#54](https://github.com/rosjava/android_remocons/issues/54)
- [x] headless launcher testing
- [x] nfc_rocon_writer README.md  ([#50](https://github.com/rosjava/android_remocons/issues/50))
- [x] headless launcher README.md  ([#52](https://github.com/rosjava/android_remocons/issues/52))

**Comment by dwlee** [comment]
I update headless launcher and nfc wirter.
And test the launching the listener with chatter concert.
19a3440..ea26fd8

**Comment by dwlee** [comment]
Update web app launcher and you can download here.
[hedless launcher apk](http://files.yujinrobot.com/android/apks/headless_launcher.apk)
[rocon nfc writer apk](http://files.yujinrobot.com/android/apks/rocon_nfc_writer.apk)
